### ISSUE TITLE
FDBDatabaseRunner needs a way to describe the transaction

### ISSUE THREAD

**Issue by scgray** [FoundationDB/fdb-record-layer#1251]
`FDBDatabaseRunner` is handed a lambda, creates a transaction, hands it to the lambda, then attempts to commit, and repeated this action as needed on retryable errors.  Unfortunately, from a logging perspective when you have, say, conflicts, they appear as exceptions tin the log that provide virtually no value to identify what work was being done, such as:

```
java.util.concurrent.CompletionException: com.apple.foundationdb.FDBException: Transaction not committed due to conflict with another transaction
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:367)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:376)
	at java.base/java.util.concurrent.CompletableFuture$UniRelay.tryFire(CompletableFuture.java:1019)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at com.apple.foundationdb.NativeFuture.marshalWhenDone(NativeFuture.java:73)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: com.apple.foundationdb.FDBException: Transaction not committed due to conflict with another transaction
	at com.apple.foundationdb.NativeFuture.Future_getError(Native Method)
	at com.apple.foundationdb.FutureVoid.getIfDone_internal(FutureVoid.java:35)
	at com.apple.foundationdb.FutureVoid.getIfDone_internal(FutureVoid.java:25)
	at com.apple.foundationdb.NativeFuture.marshalWhenDone(NativeFuture.java:60)
	... 8 more
```

I propose that `FDBDatabaseRunner` should accept  basic string title and a lambda that produces a `LoggableKeysAndValues` (or maybe just a `Map` of keys and values). These details will be included with each exception that is logged.

**Comment by scgray** [comment]
It turns out `FDBDatabaseRunner` does have a way to include useful information (`additionalLoggingDetails`)
