### ISSUE TITLE
Scanning a store with a limit can result in "attempted to return a result with NoNextReason of SOURCE_EXHAUSTED but a non-end continuation"

### ISSUE THREAD

**Issue by alecgrieser** [FoundationDB/fdb-record-layer#1294]
When scanning a record store with a limit, if just the right combination of things happen, it's possible to get the error `attempted to return a result with NoNextReason of SOURCE_EXHAUSTED but a non-end continuation`. On d17664ff507cfe, the stack trace looks like:

```
com.apple.foundationdb.record.RecordCoreException: attempted to return a result with NoNextReason of SOURCE_EXHAUSTED but a non-end continuation
            at com.apple.foundationdb.record.RecordCursorResult.withoutNextValue(RecordCursorResult.java:257)
            at com.apple.foundationdb.record.provider.foundationdb.SplitHelper$KeyValueUnsplitter.onNext(SplitHelper.java:658)
            at com.apple.foundationdb.record.cursors.MapPipelinedCursor.tryToFillPipeline(MapPipelinedCursor.java:121)
            at com.apple.foundationdb.async.AsyncUtil$LoopPartial.apply(AsyncUtil.java:355)
            at com.apple.foundationdb.async.AsyncUtil$LoopPartial.run(AsyncUtil.java:378)
            at com.apple.foundationdb.async.AsyncUtil.whileTrue(AsyncUtil.java:432)
            at com.apple.foundationdb.record.cursors.MapPipelinedCursor.onNext(MapPipelinedCursor.java:79)
            at com.apple.foundationdb.record.provider.common.StoreTimer$1.onNext(StoreTimer.java:809)
            at com.apple.foundationdb.record.RecordCursor.getNext(RecordCursor.java:239)
```

Which means that the scanning code isn't quite handling all of the various states correctly.

**Comment by alecgrieser** [comment]
I believe this happens if we have a store where the last record is a split record and also a limit is hit while reading the last record.
