### ISSUE TITLE
OnlineIndexerIndexFromIndexTest.testIndexFromIndexPersistentContinuePreviousByRecords() sometimes fails with "runner has been closed"

### ISSUE THREAD

**Issue by alecgrieser** [FoundationDB/fdb-record-layer#1296]
When running tests in CI, I saw the `testIndexFromIndexPersistentContinuePreviousByRecords` test fail with "runner has been closed" errors, though it only happens intermittently.

The stack trace is:

```
java.util.concurrent.CompletionException: com.apple.foundationdb.record.provider.foundationdb.FDBDatabaseRunner$RunnerClosed: runner has been closed
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1063)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
	at com.apple.foundationdb.record.provider.foundationdb.FDBDatabaseRunnerImpl.close(FDBDatabaseRunnerImpl.java:352)
	at com.apple.foundationdb.record.provider.foundationdb.IndexingCommon.close(IndexingCommon.java:200)
	at com.apple.foundationdb.record.provider.foundationdb.OnlineIndexer.close(OnlineIndexer.java:398)
	at com.apple.foundationdb.record.provider.foundationdb.OnlineIndexerIndexFromIndexTest.buildSrcIndex(OnlineIndexerIndexFromIndexTest.java:69)
```

The stack trace is hopefully helpful at determining where the runner is being used after closure, though it will require some digging to figure out where it be closed.

**Comment by alecgrieser** [comment]
This caused the tests for #1295 to fail, but only for one of the PRB jobs

**Comment by nblintao** [comment]
`com.apple.foundationdb.record.provider.foundationdb.OnlineIndexerIndexFromIndexTest.testIndexFromIndexPersistentContinuePreviousByIndex()` also have this problem. Looks same
https://fdb-record-layer-ci.foundationdb.org/job/prb-proto3/2550/testReport/junit/com.apple.foundationdb.record.provider.foundationdb/OnlineIndexerIndexFromIndexTest/testIndexFromIndexPersistentContinuePreviousByIndex__/
