### ISSUE TITLE
Lucene Scoring Weighting Phase: Sequential Database Activity

### ISSUE THREAD

**Issue by jleach4** [FoundationDB/fdb-record-layer#1697]
Major phases of Lucene Query for data access:

1. IndexSearcher Open
2. Term Weights
3. IndexSearcher Probe
4. Scoring Weighting***

** 1 Sequential call per Leaf
`com.apple.foundationdb.record.lucene.directory.FDBDirectory.readBlock(FDBDirectory.java:357)
	at com.apple.foundationdb.record.lucene.directory.FDBIndexInput.readBlock(FDBIndexInput.java:130)
	at com.apple.foundationdb.record.lucene.directory.FDBIndexInput.seek(FDBIndexInput.java:184)
	at org.apache.lucene.codecs.lucene84.LuceneOptimizedPostingsReader$BlockDocsEnum.reset(LuceneOptimizedPostingsReader.java:365)
	at org.apache.lucene.codecs.lucene84.LuceneOptimizedPostingsReader.postings(LuceneOptimizedPostingsReader.java:250)
	at org.apache.lucene.codecs.lucene84.LuceneOptimizedPostingsReader.impacts(LuceneOptimizedPostingsReader.java:269)
	at org.apache.lucene.codecs.blocktree.LuceneOptimizedSegmentTermsEnum.impacts(LuceneOptimizedSegmentTermsEnum.java:1019)
	at org.apache.lucene.search.SynonymQuery$SynonymWeight.scorer(SynonymQuery.java:313)
	at org.apache.lucene.search.Weight.bulkScorer(Weight.java:182)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:656)`

**Comment by alecgrieser** [comment]
Resolved by #1698
