### ISSUE TITLE
Lucene Term Weights Phase: Sequential Database Activity

### ISSUE THREAD

**Issue by jleach4** [FoundationDB/fdb-record-layer#1700]
Major phases of Lucene Query for data access:

1. IndexSearcher Open
2. Term Weights***
3. IndexSearcher Probe
4. Scoring Weighting

Here is the call stack in the code…

`com.apple.foundationdb.record.lucene.directory.FDBIndexInput.readBlock(FDBIndexInput.java:130)
	at com.apple.foundationdb.record.lucene.directory.FDBIndexInput.seek(FDBIndexInput.java:184)
	at org.apache.lucene.codecs.blocktree.LuceneOptimizedSegmentTermsEnumFrame.loadBlock(LuceneOptimizedSegmentTermsEnumFrame.java:171)
	at org.apache.lucene.codecs.blocktree.LuceneOptimizedSegmentTermsEnum.seekExact(LuceneOptimizedSegmentTermsEnum.java:515)
	at org.apache.lucene.index.TermStates.loadTermsEnum(TermStates.java:124)
	at org.apache.lucene.index.TermStates.build(TermStates.java:109)
	at org.apache.lucene.search.SynonymQuery$SynonymWeight.<init>(SynonymQuery.java:237)
	at org.apache.lucene.search.SynonymQuery.createWeight(SynonymQuery.java:211)
	at org.apache.lucene.search.IndexSearcher.createWeight(IndexSearcher.java:724)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:591)
	at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:419)
	at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:430)
	at com.apple.foundationdb.record.lucene.LuceneRecordCursor.performScan(LuceneRecordCursor.java:308)`

**Comment by MMcM** [comment]
Addressed by #1701.
