### ISSUE TITLE
Fix BufferOverflowException triggered by FDBIndexOutput

### ISSUE THREAD

**Issue by jjezra** [FoundationDB/fdb-record-layer#2345]

**Comment by jjezra** [comment]
exception="java.nio.BufferOverflowException
	at java.base/java.nio.HeapByteBuffer.put(HeapByteBuffer.java:221)
	at com.apple.foundationdb.record.lucene.directory.FDBIndexOutput.writeBytes(FDBIndexOutput.java:201)
	at org.apache.lucene.codecs.lucene80.Lucene80DocValuesConsumer.addTermsDict(Lucene80DocValuesConsumer.java:753)
	at org.apache.lucene.codecs.lucene80.Lucene80DocValuesConsumer.doAddSortedField(Lucene80DocValuesConsumer.java:682)
	at org.apache.lucene.codecs.lucene80.Lucene80DocValuesConsumer.addSortedField(Lucene80DocValuesConsumer.java:633)
	at org.apache.lucene.codecs.perfield.PerFieldDocValuesFormat$FieldsWriter.addSortedField(PerFieldDocValuesFormat.java:119)
	at org.apache.lucene.index.SortedDocValuesWriter.flush(SortedDocValuesWriter.java:150)
	at org.apache.lucene.index.DefaultIndexingChain.writeDocValues(DefaultIndexingChain.java:348)
	at org.apache.lucene.index.DefaultIndexingChain.flush(DefaultIndexingChain.java:228)
	at org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:350)
	at org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:476)
