### ISSUE TITLE
Make lucene tests with random seeds stable

### ISSUE THREAD

**Issue by ScottDugas** [FoundationDB/fdb-record-layer#2480]
Make lucene tests with random seeds stable

Right now, if you run the lucene tests with a random seed they will fail moderately often. We should change it so that they either pass, or if there is a known issue (such as Lucene trying to use our codec with a different directory), we will use assumptions to skip the test.

**Comment by ScottDugas** [comment]
`LuceneOptimizedPointsFormatTest.testAddIndexes` fails with:
```
org.junit.ComparisonFailure: expected:<_0.[cfs]> but was:<_0.[fsf]>
    at __randomizedtesting.SeedInfo.seed([57071E4365FA2B0E:E87D1748C5B83B39]:0)
    at org.junit.Assert.assertEquals(Assert.java:117)
    at org.junit.Assert.assertEquals(Assert.java:146)
    at com.apple.foundationdb.record.lucene.codec.TestFDBDirectory.openInput(TestFDBDirectory.java:166)
```

**Comment by ScottDugas** [comment]
`LuceneOptimizedPointsFormatTest.testOneDimEqual` fails with:
```
com.apple.foundationdb.record.RecordCoreException: java.util.concurrent.ExecutionException: com.apple.foundationdb.record.RecordCoreException: File Reference missing for open IndexInput
    at __randomizedtesting.SeedInfo.seed([8987B24FB10B0D0B:B01E0ABA78438491]:0)
```

Similarly `LuceneOptimizedPointsFormatTest.testOneDimEqual` fails with:
```
com.apple.foundationdb.record.RecordCoreException: java.util.concurrent.ExecutionException: com.apple.foundationdb.record.RecordCoreException: File Reference missing for open IndexInput
    at __randomizedtesting.SeedInfo.seed([8987B24FB10B0D0B:B01E0ABA78438491]:0)
```
