### ISSUE TITLE
LuceneIndexMaintenanceTest > flakyMerge(true, true, true, 5, -3487483610997135943, false) fails

### ISSUE THREAD

**Issue by ScottDugas** [FoundationDB/fdb-record-layer#2670]
```
LuceneIndexMaintenanceTest > flakyMerge(boolean, boolean, boolean, int, long, boolean) > com.apple.foundationdb.record.lucene.LuceneIndexMaintenanceTest.flakyMerge(boolean, boolean, boolean, int, long, boolean)[6] FAILED
    org.opentest4j.AssertionFailedError: Group: (0), partition: 0 ==> 
expected: <[(-1, [0, 1001], [0, 1000]), (-1, [0, 1002], [0, 999]), (-1, [0, 1003], [0, 998]), (-1, [0, 1004], [0, 997]), (-1, [0, 1005], [0, 996]), (-1, [0, 1006], [0, 995]), (-1, [0, 1007], [0, 994]), (-1, [0, 1008], [0, 993]), (-1, [0, 1009], [0, 992]), (-1, [0, 1010], [0, 991]), (-1, [0, 1011], [0, 990]), (-1, [0, 1012], [0, 989]), (-1, [0, 1013], [0, 988]), (-1, [0, 1014], [0, 987])]> 
but was:  <[(-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1001], [0, 1000]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1003], [0, 998]), (-1, [0, 1004], [0, 997]), (-1, [0, 1004], [0, 997]), (-1, [0, 1004], [0, 997]), (-1, [0, 1004], [0, 997]), (-1, [0, 1004], [0, 997]), (-1, [0, 1005], [0, 996]), (-1, [0, 1005], [0, 996]), (-1, [0, 1005], [0, 996]), (-1, [0, 1005], [0, 996]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1006], [0, 995]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1007], [0, 994]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1008], [0, 993]), (-1, [0, 1009], [0, 992]), (-1, [0, 1009], [0, 992]), (-1, [0, 1009], [0, 992]), (-1, [0, 1009], [0, 992]), (-1, [0, 1009], [0, 992]), (-1, [0, 1009], [0, 992]), (-1, [0, 1009], [0, 992]), (-1, [0, 1009], [0, 992]), (-1, [0, 1010], [0, 991]), (-1, [0, 1010], [0, 991]), (-1, [0, 1010], [0, 991]), (-1, [0, 1010], [0, 991]), (-1, [0, 1010], [0, 991]), (-1, [0, 1010], [0, 991]), (-1, [0, 1010], [0, 991]), (-1, [0, 1011], [0, 990]), (-1, [0, 1011], [0, 990]), (-1, [0, 1011], [0, 990]), (-1, [0, 1011], [0, 990]), (-1, [0, 1011], [0, 990]), (-1, [0, 1011], [0, 990]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1012], [0, 989]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1013], [0, 988]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987]), (-1, [0, 1014], [0, 987])]>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1135)
        at app//com.apple.foundationdb.record.lucene.LuceneIndexTestValidator.validatePrimaryKeySegmentIndex(LuceneIndexTestValidator.java:300)
        at app//com.apple.foundationdb.record.lucene.LuceneIndexTestValidator.validate(LuceneIndexTestValidator.java:199)
        at app//com.apple.foundationdb.record.lucene.LuceneIndexMaintenanceTest.flakyMerge(LuceneIndexMaintenanceTest.java:392)
```

**Comment by ScottDugas** [comment]
I believe this is another example:
```
LuceneIndexMaintenanceTest > flakyMerge(false, true, true, 33, -1089113174774589435, true) (8,760ms)
org.opentest4j.AssertionFailedError: Group: (), partition: 0 ==> 
expected: <[(-1, [0, 1002], [0, 999]), (-1, [0, 1003], [0, 998]), (-1, [0, 1004], [0, 997]), (-1, [0, 1005], [0, 996]), (-1, [0, 1006], [0, 995]), (-1, [0, 1007], [0, 994]), (-1, [0, 1008], [0, 993]), (-1, [0, 1009], [0, 992]), (-1, [0, 1010], [0, 991]), (-1, [0, 1011], [0, 990]), (-1, [0, 1012], [0, 989]), (-1, [0, 1013], [0, 988]), (-1, [0, 1014], [0, 987]), (-1, [0, 1015], [0, 986]), (-1, [0, 1016], [0, 985]), (-1, [0, 1017], [0, 984]), (-1, [0, 1018], [0, 983]), (-1, [0, 1019], [0, 982]), (-1, [0, 1020], [0, 981]), (-1, [0, 1021], [0, 980]), (-1, [0, 1022], [0, 979]), (-1, [0, 1023], [0, 978]), (-1, [0, 1024], [0, 977]), (-1, [0, 1025], [0, 976]), (-1, [0, 1026], [0, 975]), (-1, [0, 1027], [0, 974]), (-1, [0, 1028], [0, 973]), (-1, [0, 1029], [0, 972]), (-1, [0, 1030], [0, 971]), (-1, [0, 1031], [0, 970]), (-1, [0, 1032], [0, 969]), (-1, [0, 1033], [0, 968]), (-1, [0, 1034], [0, 967]), (-1, [0, 1035], [0, 966]), (-1, [0, 1036], [0, 965]), (-1, [0, 1037], [0, 964]), (-1, [0, 1038], [0, 963]), (-1, [0, 1039], [0, 962]), (-1, [0, 1040], [0, 961]), (-1, [0, 1041], [0, 960]), (-1, [0, 1042], [0, 959]), (-1, [0, 1043], [0, 958]), (-1, [0, 1044], [0, 957]), (-1, [0, 1045], [0, 956]), (-1, [0, 1046], [0, 955]), (-1, [0, 1047], [0, 954]), (-1, [0, 1048], [0, 953]), (-1, [0, 1049], [0, 952]), (-1, [0, 1050], [0, 951]), (-1, [0, 1051], [0, 950]), (-1, [0, 1052], [0, 949]), (-1, [0, 1053], [0, 948]), (-1, [0, 1054], [0, 947]), (-1, [0, 1055], [0, 946]), (-1, [0, 1056], [0, 945]), (-1, [0, 1057], [0, 944]), (-1, [0, 1058], [0, 943]), (-1, [0, 1059], [0, 942]), (-1, [0, 1060], [0, 941]), (-1, [0, 1061], [0, 940]), (-1, [0, 1062], [0, 939]), (-1, [0, 1063], [0, 938]), (-1, [0, 1064], [0, 937]), (-1, [0, 1065], [0, 936]), (-1, [0, 1066], [0, 935]), (-1, [0, 1067], [0, 934]), (-1, [0, 1068], [0, 933]), (-1, [0, 1069], [0, 932]), (-1, [0, 1070], [0, 931]), (-1, [0, 1071], [0, 930]), (-1, [0, 1072], [0, 929]), (-1, [0, 1073], [0, 928]), (-1, [0, 1074], [0, 927]), (-1, [0, 1075], [0, 926]), (-1, [0, 1076], [0, 925]), (-1, [0, 1077], [0, 924]), (-1, [0, 1078], [0, 923]), (-1, [0, 1079], [0, 922])]> 
but was:  <[(-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1002], [0, 999]), (-1, [0, 1003], [0, 998]), (-1, [0, 1004], [0, 997]), (-1, [0, 1005], [0, 996]), (-1, [0, 1006], [0, 995]), (-1, [0, 1007], [0, 994]), (-1, [0, 1008], [0, 993]), (-1, [0, 1009], [0, 992]), (-1, [0, 1010], [0, 991]), (-1, [0, 1011], [0, 990]), (-1, [0, 1012], [0, 989]), (-1, [0, 1013], [0, 988]), (-1, [0, 1014], [0, 987]), (-1, [0, 1015], [0, 986]), (-1, [0, 1016], [0, 985]), (-1, [0, 1017], [0, 984]), (-1, [0, 1018], [0, 983]), (-1, [0, 1019], [0, 982]), (-1, [0, 1020], [0, 981]), (-1, [0, 1021], [0, 980]), (-1, [0, 1022], [0, 979]), (-1, [0, 1023], [0, 978]), (-1, [0, 1024], [0, 977]), (-1, [0, 1025], [0, 976]), (-1, [0, 1026], [0, 975]), (-1, [0, 1027], [0, 974]), (-1, [0, 1028], [0, 973]), (-1, [0, 1029], [0, 972]), (-1, [0, 1030], [0, 971]), (-1, [0, 1031], [0, 970]), (-1, [0, 1032], [0, 969]), (-1, [0, 1033], [0, 968]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1034], [0, 967]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1035], [0, 966]), (-1, [0, 1036], [0, 965]), (-1, [0, 1037], [0, 964]), (-1, [0, 1038], [0, 963]), (-1, [0, 1039], [0, 962]), (-1, [0, 1040], [0, 961]), (-1, [0, 1041], [0, 960]), (-1, [0, 1042], [0, 959]), (-1, [0, 1043], [0, 958]), (-1, [0, 1044], [0, 957]), (-1, [0, 1045], [0, 956]), (-1, [0, 1046], [0, 955]), (-1, [0, 1047], [0, 954]), (-1, [0, 1048], [0, 953]), (-1, [0, 1049], [0, 952]), (-1, [0, 1050], [0, 951]), (-1, [0, 1051], [0, 950]), (-1, [0, 1052], [0, 949]), (-1, [0, 1053], [0, 948]), (-1, [0, 1054], [0, 947]), (-1, [0, 1055], [0, 946]), (-1, [0, 1056], [0, 945]), (-1, [0, 1057], [0, 944]), (-1, [0, 1058], [0, 943]), (-1, [0, 1059], [0, 942]), (-1, [0, 1060], [0, 941]), (-1, [0, 1061], [0, 940]), (-1, [0, 1062], [0, 939]), (-1, [0, 1063], [0, 938]), (-1, [0, 1064], [0, 937]), (-1, [0, 1065], [0, 936]), (-1, [0, 1066], [0, 935]), (-1, [0, 1067], [0, 934]), (-1, [0, 1068], [0, 933]), (-1, [0, 1069], [0, 932]), (-1, [0, 1070], [0, 931]), (-1, [0, 1071], [0, 930]), (-1, [0, 1072], [0, 929]), (-1, [0, 1073], [0, 928]), (-1, [0, 1074], [0, 927]), (-1, [0, 1075], [0, 926]), (-1, [0, 1076], [0, 925]), (-1, [0, 1077], [0, 924]), (-1, [0, 1078], [0, 923]), (-1, [0, 1079], [0, 922])]>
	at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
	at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1156)
	at app//com.apple.foundationdb.record.lucene.LuceneIndexTestValidator.validatePrimaryKeySegmentIndex(LuceneIndexTestValidator.java:344)
	at app//com.apple.foundationdb.record.lucene.LuceneIndexTestValidator.validatePartitionedGroup(LuceneIndexTestValidator.java:202)
	at app//com.apple.foundationdb.record.lucene.LuceneIndexTestValidator.validate(LuceneIndexTestValidator.java:134)
	at app//com.apple.foundationdb.record.lucene.LuceneIndexMaintenanceTest.flakyMerge(LuceneIndexMaintenanceTest.java:471)
```
