### ISSUE TITLE
Test failure in MoreAsyncUtilTest.getWithDeadlineRunsOnExecutor

### ISSUE THREAD

**Issue by alecgrieser** [FoundationDB/fdb-record-layer#2971]
There was a test failure encountered during nightly tests:

```
MoreAsyncUtilTest > getWithDeadlineRunsOnExecutor() FAILED
    org.opentest4j.AssertionFailedError: expected: <test-deadline-exceeded-thread-0> but was: <Test worker>
        at app//org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
        at app//org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
        at app//org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1145)
        at app//com.apple.foundationdb.async.MoreAsyncUtilTest.getWithDeadlineRunsOnExecutor(MoreAsyncUtilTest.java:136)
```

That test asserts that the right executor is used when running a call back. However, there are conditions where the callback can actually run on the current thread, and that's apparently what was hit during this test run.

**Comment by ScottDugas** [comment]
The test was introduced with: https://github.com/FoundationDB/fdb-record-layer/pull/2965
