### ISSUE TITLE
Test versionstampIndexDeserialization seems broken

### ISSUE THREAD

**Issue by amouehsan** [FoundationDB/fdb-record-layer#354]
While working on PR #320, I uncovered a bug in the test `MetaDataProtoTest.versionstampIndexDeserialization() `. It looks like that it adds an index that  `validateIndex()` cannot validate: 

```
Descriptor MyModernRecord does not have field: header
com.apple.foundationdb.record.metadata.expressions.KeyExpression$InvalidExpressionException: Descriptor MyModernRecord does not have field: header
	at com.apple.foundationdb.record.metadata.expressions.FieldKeyExpression.validate(FieldKeyExpression.java:90)
	at com.apple.foundationdb.record.metadata.expressions.FieldKeyExpression.validate(FieldKeyExpression.java:84)
	at com.apple.foundationdb.record.metadata.expressions.NestingKeyExpression.validate(NestingKeyExpression.java:91)
	at com.apple.foundationdb.record.metadata.Index.validate(Index.java:392)
	at com.apple.foundationdb.record.metadata.MetaDataValidator.validateIndexForRecordType(MetaDataValidator.java:108)
	at com.apple.foundationdb.record.metadata.IndexValidator.validateIndexForRecordType(IndexValidator.java:52)
	at com.apple.foundationdb.record.metadata.MetaDataValidator.validateIndexForRecordTypes(MetaDataValidator.java:103)
	at com.apple.foundationdb.record.metadata.IndexValidator.validate(IndexValidator.java:48)
	at com.apple.foundationdb.record.provider.foundationdb.indexes.VersionIndexMaintainerFactory$1.validate(VersionIndexMaintainerFactory.java:56)
	at com.apple.foundationdb.record.metadata.MetaDataValidator.validateIndex(MetaDataValidator.java:93)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.apple.foundationdb.record.metadata.MetaDataValidator.validate(MetaDataValidator.java:57)
	at com.apple.foundationdb.record.RecordMetaDataBuilder.build(RecordMetaDataBuilder.java:934)
	at com.apple.foundationdb.record.metadata.MetaDataProtoTest.versionstampIndexDeserialization(MetaDataProtoTest.java:303)
```

It was hidden because we build a meta-data with no record types. Hence, this piece becomes no-op:
 
```
public void validateIndexForRecordTypes(@Nonnull Index index, @Nonnull IndexValidator indexValidator) {
        for (RecordType recordType : metaData.recordTypesForIndex(index)) {
            indexValidator.validateIndexForRecordType(recordType, this);
        }
    }
```

Note that the builder of the test does not process the extension options, and hence doesn't extract the primary keys / indexes. That means `RecordMetaDataBuilder.build()` will not add record types to the meta-data. On top of master, the bug can be uncovered by changing:

```
RecordMetaData metaData = RecordMetaData.newBuilder().addDependencies(BASE_DEPENDENCIES)
                .setRecords(protoBuilder.build())
                .getRecordMetaData();
```

to 

```
RecordMetaData metaData = RecordMetaData.newBuilder().addDependencies(BASE_DEPENDENCIES)
                .setRecords(protoBuilder.build(), true)
                .getRecordMetaData();
```

I can temporarily make the test pass by not validating the built the record meta-data. but we may want to eventually fix this by doing the following two:
- If a record meta-data that has no record types is invalid, we should probably check it and fail its validation. 
- we should fix the test itself, by processing the extension options and fixing the index addition. 

Filing this issue, so we can get to it later.

**Comment by amouehsan** [comment]
> Why does this throw the error it does and not "Record type MyModernRecord must have a primary key"?

Because this is on top of the master tree and doesn't have my change.

**Comment by alecgrieser** [comment]
Oh, I see. What change was made to make it throw this error (as the test is passing on master, right)?
