### ISSUE TITLE
FDBDatabaseRunnerTest.testRestoreMdc is somewhat flaky

### ISSUE THREAD

**Issue by alecgrieser** [FoundationDB/fdb-record-layer#580]
The PRB build for #578 failed due to an error in `FDBDatabaseRunnerTest.testRestoreMdc`. The error was:

```
org.opentest4j.AssertionFailedError: expected: <[{loc=runner runAsync, attempt=0, outer=Echidna}, {loc=supplyAsync, attempt=0, restored=Platypus}, {loc=runner runAsync, attempt=1, restored=Platypus}, {loc=supplyAsync, attempt=1, restored=Platypus}, {loc=handle, attempt=2, restored=Platypus}]> but was: <[{loc=runner runAsync, attempt=0, outer=Echidna}, {loc=supplyAsync, attempt=0, restored=Platypus}, {loc=runner runAsync, attempt=1, restored=Platypus}, {loc=supplyAsync, attempt=1, restored=Platypus}, {loc=handle, attempt=2, outer=Echidna}]>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:52)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:186)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:181)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:486)
	at com.apple.foundationdb.record.provider.foundationdb.FDBDatabaseRunnerTest.testRestoreMdc(FDBDatabaseRunnerTest.java:414)
```

Here's the relevant portion of `testRestoreMdc`:

https://github.com/FoundationDB/fdb-record-layer/blob/7a9eba338b6faa819b6da9f318f370e2b72bf9d5/fdb-record-layer-core/src/test/java/com/apple/foundationdb/record/provider/foundationdb/FDBDatabaseRunnerTest.java#L387-L401

There's then an assert to make sure the correct context is used in each context. The failure indicates that the `handle` lambda was executed using the wrong MDC. In particular, it used the outer thread's MDC rather than the "restored" one.

I was unable to reproduce locally, but I think this is what happened:

1. The runner ran its first loop on the outer thread (without the restored MDC).
1. The runner retried, which happens on a thread with the restored MDC.
1. All of this happened before the outer thread could call `.handle` (or at least before `handle` could add the callback).
1. Then when `.handle` was called, it was added to an already completed future, so the lambda executed on the outer thread (without the restored MDC).

I therefore don't think this is a bug with the actual context restoring runnable, just a race condition with the test. I guess it depends on what this test is supposed to be testing, but this could:

* Use `.handleAsync` instead of `.handle`. This would show that the executor works, I suppose, though it wouldn't test that the callbacks are executed with the right executor, I suppose (though maybe we don't need to test that).
* Do something like add a "signaling" future within the test that could be used to make sure that the `.handle` method is called on an incomplete future, and then only complete the future once all of the callbacks are set up.

**Comment by alecgrieser** [comment]
@ScottDugas, do you have anything you'd want to add about this issue? If my diagnosis sounds reasonable to you, if you have insight into which solution (or if there's a third solution), that would be good to know.
