### ISSUE TITLE
OnlineIndexerSimpleTest.testConfigLoader() test failure

### ISSUE THREAD

**Issue by scgray** [FoundationDB/fdb-record-layer#936]
During a PRB run for https://github.com/FoundationDB/fdb-record-layer/pull/926, this test failed with:

```
org.opentest4j.AssertionFailedError: expected: <95> but was: <94>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:510)
	at com.apple.foundationdb.record.provider.foundationdb.OnlineIndexerSimpleTest.testConfigLoader(OnlineIndexerSimpleTest.java:876)
```

**Comment by nblintao** [comment]
@jjezra Not same, but it might be related to the issue you found.

**Comment by MMcM** [comment]
The failing condition asserts about the consistency of the state of a running index builder: there is no means of guaranteeing that `getLimit` and `getConfigLoaderInvocationCount` match when two unsynchronized calls are needed to get them.
