### ISSUE TITLE
RankedSetTest.concurrentAdd() sometimes fails with a transaction conflict

### ISSUE THREAD

**Issue by nschiefer** [FoundationDB/fdb-record-layer#943]
From a proto2 build on #929:

```
com.apple.foundationdb.async.RankedSetTest &gt; concurrentAdd() FAILED
    java.util.concurrent.CompletionException: com.apple.foundationdb.FDBException: Transaction not committed due to conflict with another transaction
        at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:375)
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:1934)
        at com.apple.foundationdb.async.RankedSetTest.concurrentAdd(RankedSetTest.java:194)

        Caused by:
        com.apple.foundationdb.FDBException: Transaction not committed due to conflict with another transaction
```

**Comment by nschiefer** [comment]
Over to @alecgrieser for triage.
