### ISSUE TITLE
Event analysis is fooled by incomplete version stamps

### ISSUE THREAD

**Issue by MMcM** [FoundationDB/fdb-record-layer#980]
such as might be found in write records.

 java.lang.ArrayIndexOutOfBoundsException: arraycopy: length -1 is negative
	at java.base/java.util.Arrays.copyOfRange(Arrays.java:4031)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:141)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.addInternal(TupleKeyCountTree.java:143)
	at com.apple.foundationdb.clientlog.TupleKeyCountTree.add(TupleKeyCountTree.java:132)
	at com.apple.foundationdb.clientlog.DatabaseClientLogEventCounter.addKey(DatabaseClientLogEventCounter.java:109)
	at com.apple.foundationdb.clientlog.DatabaseClientLogEventCounter.addCommit(DatabaseClientLogEventCounter.java:158)
	at com.apple.foundationdb.clientlog.DatabaseClientLogEventCounter.accept(DatabaseClientLogEventCounter.java:81)
	at com.apple.foundationdb.clientlog.DatabaseClientLogEvents$EventRunner.accept(DatabaseClientLogEvents.java:187)
	at com.apple.foundationdb.clientlog.DatabaseClientLogEvents$EventRunner.accept(DatabaseClientLogEvents.java:89)
	at com.apple.foundationdb.clientlog.FDBClientLogEvents.lambda$deserializeEvents$1(FDBClientLogEvents.java:593)
	at com.apple.foundationdb.async.AsyncUtil$LoopPartial.apply(AsyncUtil.java:355)
	at com.apple.foundationdb.async.AsyncUtil$LoopPartial.run(AsyncUtil.java:378)
	at com.apple.foundationdb.async.AsyncUtil.whileTrue(AsyncUtil.java:432)
	at com.apple.foundationdb.async.AsyncUtil.whileTrue(AsyncUtil.java:420)
	at com.apple.foundationdb.clientlog.FDBClientLogEvents.deserializeEvents(FDBClientLogEvents.java:564)
	at com.apple.foundationdb.clientlog.FDBClientLogEvents$EventDeserializer.accept(FDBClientLogEvents.java:669)

**Comment by MMcM** [comment]
The problem is thinking that you can use `Tuple.from(childObject).getPackedSize()` to move a byte array pointer along through the encoded tuple for each element.
